on:
  workflow_call:

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - model_name: minishlab/potion-base-4M
            model_tag_name: minishlab-potion-base-4M
          - model_name: minishlab/potion-base-8M
            model_tag_name: minishlab-potion-base-8M
          - model_name: minishlab/potion-base-32M
            model_tag_name: minishlab-potion-base-32M
          - model_name: minishlab/potion-multilingual-128M
            model_tag_name: minishlab-potion-multilingual-128M
          - model_name: minishlab/potion-retrieval-32M
            model_tag_name: minishlab-potion-retrieval-32M
    env:
      LOCAL_REPO: model2vec-inference
      REMOTE_REPO: semitechnologies/model2vec-inference
      MODEL_NAME: ${{matrix.model_name}}
      MODEL_TAG_NAME: ${{matrix.model_tag_name}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          cache: 'pip' # caching pip dependencies
      - name: Login to Docker Hub
        if: ${{ !github.event.pull_request.head.repo.fork }}  # no PRs from fork
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and test
        run: |
          cicd/build.sh
          cicd/test.sh
      - name: Deploy
        if: ${{ !github.event.pull_request.head.repo.fork && startsWith(github.ref, 'refs/tags') }}
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          cicd/docker_push.sh
